### ISSUE TITLE
Error in loading the AI in windows.

### ISSUE THREAD

**Issue by harinicklenYT** [huwprosser/carter-voice-assistant#1]
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
done
Listening...
expected scalar type Double but found Float

**Comment by huwprosser** [comment]
> You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
> 
> done
> 
> Listening...
> 
> expected scalar type Double but found Float
> 
> 
> 
> 

This is due to a few things. Firstly the "downstream task" but can be ignored.

Secondly, it seems you need to uninstall tensorflow or create a new Conda environment with a fresh version of Python 3 and pip install the requirements.

**Comment by harinicklenYT** [comment]
what should be the version it might be that

**Comment by harinicklenYT** [comment]
I'm now getting this which is the same one as other person 
    Error 259 for command:
        play temp.mp3 wait
    The driver cannot recognize the specified command parameter.

    Error 259 for command:
        play temp.mp3 wait
    The driver cannot recognize the specified command parameter. 

![image](https://user-images.githubusercontent.com/109876494/181522955-8b63097d-a0e9-42d6-a367-cd401b875ae0.png)

so its not my computer.

**Comment by harinicklenYT** [comment]
![image](https://user-images.githubusercontent.com/109876494/181523262-c90b786d-ba92-416e-81b6-8465469a9819.png)

**Comment by huwprosser** [comment]
Hi Hari, which version of playsound are you using?

**Comment by harinicklenYT** [comment]
playsound 1.3.0

**Comment by harinicklenYT** [comment]
![image](https://user-images.githubusercontent.com/109876494/181590860-6ad276fe-03fb-440f-878c-d00cab6e4a1e.png)
i think we might need to call about this i have no idea on the isuue

**Comment by huwprosser** [comment]
Ok I'm just making the project a bit lighter. It seems as though the version you're using is importing libraries it doesn't need. I'll shortly be releasing a new version to hopefully get this working.

**Comment by harinicklenYT** [comment]
okay is it possible in the requirements you can put the certain version they need to be installing and when will it be released?

**Comment by huwprosser** [comment]
Yes absolutely

**Comment by harinicklenYT** [comment]
Thank you im sorry for all the fuss been really stressed lately.

**Comment by harinicklenYT** [comment]
and also i would like an invite to carter server

**Comment by harinicklenYT** [comment]
hi have you made the updated version
