### ISSUE TITLE
Not listening

### ISSUE THREAD

**Issue by Ethan-Barr** [huwprosser/carter-voice-assistant#2]
When I run app.py on my laptop. it does all of the startup but after listeining it doesnt listen at all and doesnt come up with any error.

**Comment by huwprosser** [comment]
> When I run app.py on my laptop. it does all of the startup but after listeining it doesnt listen at all and doesnt come up with any error.

Yesterday I released a new version of this repo with a fix for this on Windows. Might be worth downloading it again! 

Let me know how you get on 😎

**Comment by Ethan-Barr** [comment]
Ok I will redownload it and see what happens. Thanks for thr suggestion

**Comment by huwprosser** [comment]
How far did you get with this?

**Comment by Ethan-Barr** [comment]
Same problem. It wont listen but i think i know why because i havent set up an voice for it yet so ill do that when i next open the folder tommorow

**Comment by huwprosser** [comment]
Hi there, just checking in on this? If it's resolved could you be awesome and mark this issue as resolved?

**Comment by Ethan-Barr** [comment]
> Hi there, just checking in on this? If it's resolved could you be awesome and mark this issue as resolved?

I havent had chance to look yet but ill mark this as closed an if i have the problem ill reopen it again
