### ISSUE TITLE
How to play music

### ISSUE THREAD

**Issue by harinicklenYT** [huwprosser/carter-voice-assistant#4]
How can i get custom commands to play music

**Comment by huwprosser** [comment]
Hi! You can create custom triggers for your agent in the dashboard. Then use the API response "triggers" item to see a list of triggers that have been triggered by your user input. Once you have that, you can write your own custom function to handle, for example, playing music with perhaps a companion package like Spotipy.

**Comment by harinicklenYT** [comment]
could you put down example codes?

**Comment by huwprosser** [comment]
This issue is better suited for your own personal development and is more related to do with the Spotipy project. https://spotipy.readthedocs.io/en/master/

**Comment by harinicklendestiny121212** [comment]
Thank you i will close this issue now.
