### ISSUE TITLE
expected scalar type Double but found Float

### ISSUE THREAD

**Issue by toffbiffle** [huwprosser/carter-voice-assistant#6]
OS: Windows
py version: 3.10.4 running in a venv

After "Listening..." is prompted and something has been said I get the response.
"expected scalar type Double but found Float"

```
*Invoking app.py*
Carter Voice Client Starting...
Loading voice models. This may take a second...
Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
done
Listening...
expected scalar type Double but found Float
```

**Comment by huwprosser** [comment]
This is a common issue and appears to be to do with tensor flow versions you may have already installed, if you uninstall tensor flow: 
`pip uninstall tensorflow `

and then reinstall it:
`pip install tensorflow`

That should now work.

**Comment by toffbiffle** [comment]
oh, seams tensorflow wasnt even installed from the beginning...

after I installed tensorflow and re-run app.py I get:

```
...
Listening...
2022-08-14 12:59:25.678854: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-08-14 12:59:25.679048: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
expected scalar type Double but found Float
```

found out the reason for the cudart64_110.dll issue and installed CUDA 11.x

Unfortunatly the error with the expected scalar type persists.

I tired removing and re-installing tensorflow after I installed CUDA but it did not help.

```
Listening...
expected scalar type Double but found Float
```
remains.

**Comment by PythonProgrammerUltron** [comment]
lol this was ages ago i made a working one
