### ISSUE TITLE
Carter Api Problem 

### ISSUE THREAD

**Issue by PythonProgrammerUltron** [huwprosser/carter-voice-assistant#7]
Hello I'm Facing A Problem While Trying to Launch Carter. I am on windows and I uninstall and reinstall everything but still same issue and I'm using anaconda prompt for new environment 

Issue:
Carter Voice Client Starting...
Loading voice models. This may take a second...
Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
done
Listening...
2022-09-11 22:29:20.333647: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-09-11 22:29:20.333750: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
expected scalar type Double but found Float

**Comment by PythonProgrammerUltron** [comment]
![image](https://user-images.githubusercontent.com/113312291/189549843-1130f16b-7758-4b5f-80d8-68c1fad05325.png)


looks like a problem on your end

**Comment by huwprosser** [comment]
Hi there, there isn't an 'our end' when it comes to the pip packages that are raising this error as the Carter API is a simple REST API endpoint within the code. The issue being raised here is likely a miss-alignment of packages. I highly recommend creating a brand new Conda environment, re-cloning the project and installing all pip packages, if you get the same error, in tensorflow with pip install tensorflow. If this doesn't resolve it, come back here and I'll take a closer look at the code.

**Comment by PythonProgrammerUltron** [comment]
hello, still same issue.

**Comment by huwprosser** [comment]
Please provide a pip freeze of your environment.
